/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-29 23:48:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.planner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>CreatePlanner</title>\r\n");
      out.write("<!-- 폰트 -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nanum+Pen+Script|Ubuntu&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Ubuntu', sans-serif;\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputtext {\r\n");
      out.write("\tfont-size: 42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".planPlace {\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tbackground-color: #18a8f1;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".planPlaces {\r\n");
      out.write("\tborder: 0px solid rgba(135, 206, 235, 0.3);\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground-color: #18a8f1;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#createContent {\r\n");
      out.write("\tbackground-color: rgba(135, 206, 235, 0.4);\r\n");
      out.write("\theight: 1020px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".selectArea {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\tdisplay: inline-block\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".selectGroup {\r\n");
      out.write("\tdisplay: inline-block\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".selectdate {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 44%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div id=\"createContent\">\r\n");
      out.write("\t\t\t\t\t<form action=\"createPlanner\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: 20%; position: relative; padding: 30px 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"planerTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"inputtext\">*플래너 제목입력</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</label> <input type=\"text\" name=\"plannerTitle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control required\" id=\"planerTitle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"제목을 입력해 주세요\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"triPlace\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: 20%; padding: 30px 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"selectArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"selectbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"inputtext\">*여행장소 입력</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <br> <select name=\"largeAreaCode\" id=\"largeArea\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"required areaselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected disabled hidden>지역 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">경기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">강원</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"4\">충북</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">충남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"6\">전북</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"7\">전남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"8\">경북</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"9\">경남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">제주</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"smallAreaCode\" id=\"smallArea\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"required areaselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected disabled hidden>장소 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">경기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13\">강원</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14\">충북</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\">충남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16\">전북</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17\">전남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18\">경북</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19\">경남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00\">제주</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"selectGroup\" style=\"width: 49%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"selectbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"inputtext\">*여행 그룹선택</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label><br> <select name=\"groupCode\" id=\"tripgroup\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected disabled hidden>그룹 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">혼자 여행하기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">친구랑 여행하기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">연인이랑 여행하기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"4\">가족과 여행하기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br> <input type=\"text\" class=\"planPlaces\" readonly>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%; height: 30%; padding: 30px 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"selectdate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"datePlanner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"inputtext\">*여행 일자 선택</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <br> <input name=\"plannerStartDT\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"startPlanner\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"selectdate\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"plannerExpiry\" type=\"date\" id=\"endPlanner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"event\">이벤트</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%; padding: 30px 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"inputtext\">플래너 공개여부 설정</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=plannerPublicYN type=\"checkbox\" id=\"openplanner\"\r\n");
      out.write("\t\t\t\t\t\t\t\tchecked=\"checked\" /> <label for=\"openplanner\"> (선택 시\r\n");
      out.write("\t\t\t\t\t\t\t\t비공개) </label> <input name=\"plannerPwd\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"비밀번호 입력 \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%; height: 20%; padding: 30px 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 40%; height: 50px;\">생성</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 40%; height: 50px;\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("        \t$(\"#event\").on(\"click\",function(){\r\n");
      out.write("\t\t\tvar today = new Date(); \r\n");
      out.write("\t\t\tvar dd = today.getDate();\r\n");
      out.write("\t\t\tvar mm = today.getMonth() +1;\r\n");
      out.write("\t\t\tvar yyyy = today.getFullYear();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar startDate = $(\"#startPlanner\").val(); \r\n");
      out.write("       \t\tvar startDateArr = startDate.split('-');\r\n");
      out.write("         \r\n");
      out.write("        \tvar endDate = $(\"#endPlanner\").val(); \r\n");
      out.write("        \tvar endDateArr = endDate.split('-');\r\n");
      out.write("                 \r\n");
      out.write("        \tvar startDateCompare = new Date(startDateArr[0], parseInt(startDateArr[1])-1, startDateArr[2]);\r\n");
      out.write("        \tvar endDateCompare = new Date(endDateArr[0], parseInt(endDateArr[1])-1, endDateArr[2]);\r\n");
      out.write("         \r\n");
      out.write("        \tif(startDateCompare.getDate() > endDateCompare.getDate()) {\r\n");
      out.write("        \t\t alert(\"시작날짜와 종료날짜를 확인해 주세요.\");\r\n");
      out.write("                 \r\n");
      out.write("                 return;\t\r\n");
      out.write("        \t}\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t\tconsole.log(startDate);\r\n");
      out.write("        \t\tconsole.log(today)\r\n");
      out.write("        \t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
