/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-31 07:50:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.planner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class plannerGuide_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/slick.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- 공용 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 호환성 -->\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("<!-- 폰트 -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nanum+Pen+Script|Ubuntu&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>사용설명서</title>\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Ubuntu', sans-serif;\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div:focus {\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("\t/* border:1px dotted black; */\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("\theight: 860px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row>div {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼설정 */\r\n");
      out.write(".slider .slick-dots {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider .slick-dots li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("\tline-height: 2px;\r\n");
      out.write("\tfont-size: 26px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider .slick-dots li button {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-color: #18a8f1;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\t/* line-height: 2px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 화살표 설정 */\r\n");
      out.write(".slider .slick-prev {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: 20px;\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\t/* 문장들여쓰기 */\r\n");
      out.write("\ttext-indent: -9999px;\r\n");
      out.write("\t/* 30px/1 은 글자크기30px lineheight=1 */\r\n");
      out.write("\tfont: normal normal normal 30px/1 FontAwesome;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("/* 이미지태그를 사용할수없는 상태 */\r\n");
      out.write(".slider .slick-prev::before {\r\n");
      out.write("\tcontent: \"\\f060\";\r\n");
      out.write("\tcolor: #18a8f1;\r\n");
      out.write("\ttext-indent: 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 8px;\r\n");
      out.write("\tbottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider .slick-next {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tbottom: 20px;\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-indent: -9999px;\r\n");
      out.write("\tfont: normal normal normal 30px/1 FontAwesome;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider .slick-next::before {\r\n");
      out.write("\tcontent: \"\\f061\";\r\n");
      out.write("\tcolor: #18a8f1;\r\n");
      out.write("\ttext-indent: 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 8px;\r\n");
      out.write("\tbottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checkbox-xl .custom-control-label::before, .checkbox-xl .custom-control-label::after\r\n");
      out.write("\t{\r\n");
      out.write("\ttop: 1.2rem;\r\n");
      out.write("\twidth: 1.85rem;\r\n");
      out.write("\theight: 1.85rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checkbox-xl .custom-control-label {\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\" id=\"tutorial-container\">\r\n");
      out.write("\t\t<div class=\"m-auto\" id=\"tutorial-wrapper\">\r\n");
      out.write("\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t<h1>OurTrip 사용설명서</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slider-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t\t\t<!-- 첫번째 페이지 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../resources/guideGifs/entered.gif\" class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: #18a8f1\">Step 1</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>플래너의 비밀번호를 입력하고 'Join'버튼을 클릭해주세요!</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>비밀번호를 모른다면 참여할 수 없습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>비밀번호가 없는 플래너는 다음과 같은 화면이 나오지 않습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 첫페이지끝 -->\r\n");
      out.write("\t\t\t\t\t<!-- 두번째페이지 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../resources/guideGifs/updateDate.gif\" class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: #18a8f1\">Step 2</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>날짜를 수정한 뒤 '출발일 수정' 버튼을 클릭하면 출발일이 수정됩니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일차의 '-' 버튼을 클릭하면 일차를 삭제할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>하단의 '일정 추가' 버튼을 클릭하면 일차를 추가할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일차를 드래그하면 손쉽게 일차를 변경할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일차를 클릭하면 해당 일차의 상세 일정들을 확인할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 두번째끝 -->\r\n");
      out.write("\t\t\t\t\t<!-- 세번째페이지 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../resources/guideGifs/addSchedule.gif\" class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: #18a8f1\">Step 3</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일정 제목, 경비, 시간, 메모, 장소를 입력한 뒤 '일정 추가' 버튼을 클릭하면 일정을 추가할\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>장소의 첫 번째 입력란에 지도에서 표시하고 싶은 장소명을 입력할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>장소의 검색 입력란에 찾고싶은 장소를 입력한 뒤 검색하면 지도에 나타납니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>장소를 검색한 뒤 '맛집', '관광지', '숙소' 버튼을 클릭하여 지도상에서 확인할 수 있습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>'지도 초기화' 버튼을 클릭하면 지도상의 마커를 지울 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 세번째끝 -->\r\n");
      out.write("\t\t\t\t\t<!-- 네번째페이지 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../resources/guideGifs/updateSchedule.gif\" class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 네번째끝 -->\r\n");
      out.write("\t\t\t\t\t<!-- 5번째페이지 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: #18a8f1\">Step 4</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일차 안의 일정제목을 클릭하여 일정을 수정할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일정수정이 끝난 뒤 '저장' 버튼을 클릭하면 수정한 내용이 저장됩니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>'삭제' 버튼을 클릭하여 일정을 삭제할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일정의 '▼' 기호를 클릭하면 일정에 대한 상세정보를 확인할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>일정 지도의 마커를 클릭하면 장소명과 상세주소가 나타납니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 5번째끝 -->\r\n");
      out.write("\t\t\t\t\t<!-- 6번째페이지 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../resources/guideGifs/chatting.gif\" class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: #18a8f1\">Step 5</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>플래너에 접속한 회원들과 채팅을 이용할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 6번째끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 슬라이드끝 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 슬라이드 래퍼끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- javascript lib -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../resources/js/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 슬라이드 설정 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("       // 이미지 슬라이더\r\n");
      out.write("       $(\".slider\").slick({\r\n");
      out.write("           // 아래 누르는 버튼\r\n");
      out.write("           dots: true,\r\n");
      out.write("           autoplay : false,\r\n");
      out.write("           autoplaySpeed: 3000,\r\n");
      out.write("           arrows: true,\r\n");
      out.write("           responsive : [\r\n");
      out.write("               {\r\n");
      out.write("                   breakpoint: 768,\r\n");
      out.write("                   settings : {\r\n");
      out.write("                       arrows: true,\r\n");
      out.write("                       dots : true\r\n");
      out.write("                   }\r\n");
      out.write("               }\r\n");
      out.write("           ]\r\n");
      out.write("       });\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
